#!/usr/bin/env python3
"""
Convert binary file to C header with embedded array data
Usage: bin2header.py <input.bin> <output.h> <variable_name>
"""
import sys

def bin_to_header(input_file, output_file, var_name):
    with open(input_file, 'rb') as f:
        data = f.read()

    with open(output_file, 'w') as f:
        f.write(f"// Auto-generated from {input_file}\n")
        f.write(f"// DO NOT EDIT - Generated by bin2header.py\n\n")
        f.write(f"#ifndef {var_name.upper()}_H\n")
        f.write(f"#define {var_name.upper()}_H\n\n")

        f.write(f"static const unsigned char {var_name}[] = {{\n")

        for i, byte in enumerate(data):
            if i % 12 == 0:
                f.write("    ")
            f.write(f"0x{byte:02x}")
            if i < len(data) - 1:
                f.write(", ")
            if (i + 1) % 12 == 0:
                f.write("\n")

        if len(data) % 12 != 0:
            f.write("\n")

        f.write("};\n\n")
        f.write(f"static const unsigned int {var_name}_len = {len(data)};\n\n")
        f.write(f"#endif // {var_name.upper()}_H\n")

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input.spv> <output.h> <var_name>")
        sys.exit(1)

    bin_to_header(sys.argv[1], sys.argv[2], sys.argv[3])
    print(f"Generated {sys.argv[2]} from {sys.argv[1]}")